services:
  mongodb:
    image: docker.io/bitnami/mongodb:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0
      - MONGODB_ADVERTISED_HOSTNAME=localhost
      - MONGODB_SYSTEM_LOG_VERBOSITY=0
      - MONGODB_DISABLE_SYSTEM_LOG=false
    ports:
      - '${MONGODB_PORT:-27017}:27017'
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local
